name: Java CI with Maven

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  maven-test:
    runs-on: ubuntu-latest
    env:
      PORT: 8080

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Run Maven tests
        run: mvn test
        working-directory: ./tdd-bdd